{% set name = "xarray-tensorstore" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: de3558c08891c4a7524cf579cb271d6cc005962efd1b8601dd679b58b13a68c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - xarray
    - zarr
    - tensorstore

test:
  imports:
    - xarray_tensorstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xarray-tensorstore
  license: Apache-2.0
  summary: Xarray-TensorStore is a small library that allows opening Zarr arrays into Xarray via TensorStore
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
