{% set python_min = "3.10" %}
{% set name = "xarray-tensorstore" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f01a8182b2d09b6e9a365b206a648fd0bbbb0dd6b676b3b86864f8e52d5495e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - xarray
    - zarr
    - tensorstore

test:
  imports:
    - xarray_tensorstore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google/xarray-tensorstore
  license: Apache-2.0
  summary: Xarray-TensorStore is a small library that allows opening Zarr arrays into Xarray via TensorStore
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
