{% set name = "xarray-tensorstore" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-tensorstore-{{ version }}.tar.gz
  sha256: 2ee6f164c9f1bc43328245b8d06c21863204fcd4e6159ddd6d8867c313c1d9b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - xarray
    - zarr
    - tensorstore

test:
  imports:
    - xarray_tensorstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xarray-tensorstore
  license: Apache-2.0
  summary: Xarray-TensorStore is a small library that allows opening Zarr arrays into Xarray via TensorStore
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
